name: yeti_tips_mobile
description: "Mobile version of Yeti Tips & Till application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0  # For API calls
  provider: ^6.1.1  # For state management
  shared_preferences: ^2.2.2  # For local storage
  flutter_secure_storage: ^9.0.0  # For secure storage of tokens
  intl: ^0.19.0  # For date/number formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Add assets and fonts later as needed